project_name = "4devop"

boxes = [
    {
        :name => "app-vm-ansible",
        :box => "centos/7",
        :cpu => "100",
        :ip => "192.168.1.150",
        :ram => "512"
    }
]

Vagrant.configure("2") do |config|
    boxes.each do |box|
        config.vm.define box[:name] do |vms|
          vms.vm.box = box[:box]
          vms.vm.hostname = "ansible-#{project_name}-#{box[:name]}"
    
          vms.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--cpuexecutioncap", box[:cpu]]
            v.customize ["modifyvm", :id, "--memory", box[:ram]]
          end
    
          vms.vm.network :public_network, ip: box[:ip], bridge: "wlp2s0"
    
        #   vms.vm.provision :ansible do |ansible|
        #     ansible.playbook = "tests/vagrant.yml"
        #     ansible.verbose = "vv"
        #   end
        end
    end
end
